### PR TITLE
Fix playlunky build github actions

### PR DESCRIPTION
**Pull request by estebanfer**
The update to conan 2 shouldn't be necessary to make it work after moving back to MSVC 14.39, but it's still nice to have

### CODE REVIEW

**Comment by estebanfer** [comment]
Seems like the CI doesn't pull the latest overlunky??

**Comment by estebanfer** [comment]
ah nice, the lua website is down

**Comment by Mr-Auto** [comment]
> ah nice, the lua website is down

Maybe we can switch to getting it from github? https://github.com/lua/lua/releases
From what i saw on reddit, the website will be down couple of times in june

**Comment by Dregu** [comment]
> Maybe we can switch to getting it from github?

I've done that before because they've been down a lot, but they got it back up before I did the switch. IIRC I just added the lua repo as submodule and `set(LUA_LOCAL_DIR "lua")` and it probably worked, but it was a year ago so who knows...

**Comment by estebanfer** [comment]
My local solution to lua site being down was just adding web archive lua.org as a mirror link to a cmake file in sol2

**Comment by Dregu** [comment]
> Seems like the CI doesn't pull the latest overlunky??

Yeah so I guess you should update the submodule next and see what happens 🤞🏻

**Pull request merged**
